name: Managed CI Workflow Deployer - Repo2
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'workflow-deployment.yaml'
  schedule:
    - cron: '0 11 * * 0-6'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          path: tarun-repo-2
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          repository: Omkarprakashchavan/tarun-repo-1
          path: tarun-repo-1
      - name: Set Job event name as environment variable
        run: export RUN_EVENT=${{ github.event_name }}
      - name: Install Python modules
        run: |
          pip3 install ruamel.yaml
          pip3 install pyyaml
          pip3 install requests
          pip3 install gitpython
          ls -lrt
          # Import hashlib library (md5 method is part of it)
          python
          import hashlib
          import logging
          import os
          import sys
          import git
          import yaml
          from ruamel.yaml import YAML
          sys.path.append(f'{os.path.dirname(__file__)}/..')
          import subprocess
          from os import listdir
          from os.path import isfile, join
          import requests
          import json
          versioned_ci_repo = f'{os.path.dirname(__file__)}'
          print(versioned_ci_repo)
          repo_path = versioned_ci_repo
          repo = git.Repo(repo_path)
          main_branch = repo.heads.main
          print(main_branch)
