name: Managed CI Workflow Deployer - Repo2
on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
    paths:
      - 'workflow-deployment.yaml'
  schedule:
    - cron: '0 11 * * 0-6'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          repository: Omkarprakashchavan/tarun-repo-1
      - name: Set Job event name as environment variable
        run: export RUN_EVENT=${{ github.event_name }}
      - name: Install Python modules
        run: |
          pip3 install ruamel.yaml
          pip3 install pyyaml
          pip3 install requests
          pip3 install gitpython
          ls -lrt
        
