name: Managed CI Workflow Deployer - Repo2
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          path: tarun-repo-2
      - name: Clone the MCI repository
        uses: actions/checkout@v3.3.0
        with:
          repository: Omkarprakashchavan/tarun-repo-config
          path: tarun-repo-config
          fetch-depth: 0
      - name: Set Job event name as environment variable
        run: export RUN_EVENT=${{ github.event_name }}
      - name: Install Python modules
        env:
          GITHUB_APP_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install ruamel.yaml
          pip3 install pyyaml
          pip3 install requests
          pip3 install gitpython
          ls -lrt
          pwd
          echo "------------tarun-repo-config-------------------"
          ls -lart tarun-repo-config/
          echo "------------tarun-repo-2-------------------"
          ls -lart tarun-repo-2/
          tree -h tarun-repo-2/
          python tarun-repo-2/main.py
          # # Import hashlib library (md5 method is part of it)
          # python -c """
          # """
